#!/bin/sh

while [ ! -e $GAME_FOLDER/valve/gfx.wad ]; do
  if [ -e $GAME_FOLDER ]; then
    rm -Rf $GAME_FOLDER
  fi

  mkdir -p $GAME_FOLDER

  $HOME/steamcmd.sh \
    +login anonymous \
    +force_install_dir $GAME_FOLDER/ \
    +app_update 90 \
    +app_set_config 90 mod cstrike validate \
    +quit

  if [ -e $GAME_FOLDER/steamapps ]; then
    rm -Rf $GAME_FOLDER/steamapps/*
  else
    mkdir -p $GAME_FOLDER/steamapps
  fi

  cd $GAME_FOLDER/steamapps

  for i in 10 70 90; do
    curl "https://raw.githubusercontent.com/flyingluscas/steam-dedicated-servers/master/cstrike/manifestfiles/appmanifest_${i}.acf" \
      --output appmanifest_${i}.acf \
      --silent
  done

  $HOME/steamcmd.sh \
    +login anonymous \
    +force_install_dir $GAME_FOLDER/ \
    +app_update 90 \
    +app_set_config 90 mod cstrike validate \
    +quit
done
