#!/bin/sh

while [ ! -e /home/steam/games/cstrike/valve/gfx.wad ]; do
  if [ -e /home/steam/games/cstrike ]; then
    rm -Rf /home/steam/games/cstrike
  fi

  mkdir -p /home/steam/games/cstrike

  /home/steam/steamcmd.sh \
    +login anonymous \
    +force_install_dir /home/steam/games/cstrike/ \
    +app_update 90 \
    +app_set_config 90 mod cstrike validate \
    +quit

  if [ -e /home/steam/games/cstrike/steamapps ]; then
    rm -Rf /home/steam/games/cstrike/steamapps/*
  else
    mkdir -p /home/steam/games/cstrike/steamapps
  fi

  cp /manifestfiles/* /home/steam/games/cstrike/steamapps

  /home/steam/steamcmd.sh \
    +login anonymous \
    +force_install_dir /home/steam/games/cstrike/ \
    +app_update 90 \
    +app_set_config 90 mod cstrike validate \
    +quit
done
