#!/bin/sh

cd $GAME_FOLDER

if [ $SECURE -lt 1 ]; then
  INSECURE_FLAG="-insecure"
fi

./hlds_run \
  -game cstrike \
  -strictportbind \
  $INSECURE_FLAG \
  +hostname ${HOSTNAME} \
  +ip ${IP} \
  -port ${PORT} \
  +clientport ${CLIENT_PORT} \
  +map ${MAP} \
  -maxplayers ${MAXPLAYERS}
